### ISSUE TITLE
simple_test_{online, offline} difference

### ISSUE THREAD

**Issue by Lewis-Lu** [MCG-NJU/SparseBEV#41]
Hi,

what's the purpose of distinguish these two functions with judging the world_size ? 

Best,
Lewis

**Comment by afterthat97** [comment]
SparseBEV takes 8 consecutive frames as input.

- `simple_test_online` assumes that the frames are loaded in sequence, and we save the image features into a memory queue (or cache), so that the features of previous frames can be reused. However, it relies on sequential loading and only works on single GPU (`world_size == 1`).

- `simple_test_offline` doesn't make such assumptions and extract the features of all 8 frames for each time. It works on both single/multiple GPUs, but it is slower than `simple_test_online`.

- When measuring FPS, we use `simple_test_online` as it is the common practice.

**Comment by Lewis-Lu** [comment]
Thanks~, it matches with my guess and the code.

Best,
Lewis
